### ISSUE TITLE
Expose original context object

### ISSUE THREAD

**Issue by coreylight** [awslabs/aws-serverless-express#105]
We have a need to get to the original context object within the lambda handler, is this something that can be currently done? All I see at the moment is that the context is stringified into a header for the http request.
Thanks!

**Comment by coreylight** [comment]
Thank you for the response - but would this object have functions on it, such as `context.getRemainingTimeInMillis()` ?

**Comment by brettstack** [comment]
Right, that won't work. When I was implementing this I was looking for a way to pass it through to the Express app in its original form but this was the closest I got and have not revisited. If this isn't performance-critical, you could do something like this:

```js
// app.js
const appWrapper = (event, context) => {
  const app = express()
  app.get('/', (req, res) => {
    console.log(event, context)
    res.json(event)
  })

  return app
}
```

```js
// lambda.js
exports.handler = (event, context) => {
  const server = awsServerlessExpress.createServer(appWrapper(event, context))

  return awsServerlessExpress.proxy(server, event, context)
}
```

This incurs the instantiation cost for each invoke, instead of the recommended approach (instantiating outside the handler) which incurs it once per container.

**Comment by coreylight** [comment]
Alright, thank you. Doing something similar as the workaround - don't necessarily need to create the server on every invoke (depending on needs)
https://github.com/iopipe/examples/blob/master/node/express.js
