### ISSUE TITLE
Add support for Function URLs

### ISSUE THREAD

**Issue by connorads** [awslabs/aws-serverless-express#508]
Can skip API Gateway with newly released Function URLs
https://aws.amazon.com/about-aws/whats-new/2022/04/aws-lambda-function-urls-built-in-https-endpoints/

I presume some code changes are required.
If not, the [docs](https://github.com/vendia/serverless-express/blob/mainline/README.md?plain=1#L11) will need updating.

**Comment by pmosconi** [comment]
I tested it quite extensively this week and it works. A few points that could save time to others:

Remove CORS config from function code (unfortunately this makes it incompatible with use behind API Gateway).

Add CORS config to lambda: as of now I've been able to do it only in console, but I have an open ticket with AWS Support and will share findings. Reasons are cli doesn't create lambda execution policy and cloudformation template with serverless transform simply ignores lambda url configuration.

In setting CORS config I spent a substantial amount of time in figuring out that allowed headers must be added one by one each in in its own field: entering `Content-Type,Authorization` in a single field is accepted by the console but it will not work presumably because lambda treats it as a single header.

paolo

**Comment by jefforulez** [comment]
this already works, no code changes needed.  

these lines take care of it:
https://github.com/vendia/serverless-express/blob/mainline/src/event-sources/utils.js#L84-L86

you just need to make sure to use the new 4.x handler:  
https://github.com/vendia/serverless-express/blob/mainline/UPGRADE.md

the reason it already works is stated here:  
https://docs.aws.amazon.com/lambda/latest/dg/urls-invocation.html

"The request and response event formats follow the same schema as the Amazon API Gateway payload format version 2.0."

**Comment by joebowbeer** [comment]
Can someone suggest an addition to the docs that would make this clear?

**Comment by brett-vendia** [comment]
Closing issue. Would love an example added!
