### ISSUE TITLE
Guidance: Init wait for Promise?

### ISSUE THREAD

**Issue by joevbruno** [awslabs/aws-serverless-express#93]
Thanks for all your hard work making this package! Great job!

I am trying to resolve one issue I have encountered with little success. I am receiving the following error when running `SLS_DEBUG=* serverless invoke local -f api`:

`WARNING: Attempting to listen on socket /tmp/server05.sock, but it is already in use. This is likely as a result of a previous invocation error or timeout. Check the logs for the invocation(s) immediately prior to this for root cause, and consider increasing the timeout and/or cpu/memory allocation if this is purely as a result of a timeout. aws-serverless-express will restart the Node.js server listening on a new port and continue with this request.`

This seems to have something to do with the fact that I am exporting a function that is dependent upon a promise.  I need this to be async because it is dependent upon various async tasks like connecting to a database.

```
import { createServer, proxy } from 'aws-serverless-express';
import { createApp } from '../app';

const getApp = createApp()
  .then(createServer)
  .catch(error => console.log(error));

const app = (event, context) =>
  getApp
    .then(server => proxy(server, event, context))
    .catch(error => context.fail(JSON.stringify(error)));

export { app };
```

Any suggestions on this?

**Comment by brettstack** [comment]
If you're only getting this while running locally, you can ignore. I'll see if I can get it to not show this warning in a non-Lambda environment to reduce confusion.

**Comment by lems3** [comment]
And what if we get this error in a API Gateway/Lambda environment ?

i'm trying to start a GraphQL endpoint in an express server (we use express to make authentication easier). We had this socket error locally, but since we are on windows and we had to change code in the library for the socket to work I didn't put that much effort looking into this problem. But we also have the problem once deployed.

**Comment by brettstack** [comment]
If you get this in Lambda, it means there's an unhandled error. Check your CloudWatch logs

**Comment by lems3** [comment]
For the sake of future googlers, here's the complete story of why we had this error :  

So, on our local machines we had timeouts. We had nothing showing up in the Cloudwatch logs other than the socket error. By searching and testing, we came to the conclusion that the database connection was not working and the Lambda was timing out before the DB connection.

We use MariaDB on RDS. By looking at our setup, we remembered we placed the RDS in subnets and security groups to make it private to our AWS account. So, we had to place our Lambda in the same VPC and subnets. From there, everything started working fine (actually, not really, we had to play with VPC and NAT gateways because we needed internet access for the Lambda, but this is not in the scope of this issue).
